name: API (checks)

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - ".github/workflows/api.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "api/**"
      - ".github/workflows/api.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # This repo’s API is ESM; you already added api/package.json with { "type": "module" }.
      # We’ll just verify the function file imports cleanly in either layout.
      - name: Sanity import serverless function
        shell: bash
        run: |
          set -e
          if [ -f ./api/search.js ]; then
            node -e "import('./api/search.js').then(()=>console.log('✅ api/search.js import OK')).catch(e=>{console.error(e);process.exit(1)})"
          elif [ -f ./api/api/search.js ]; then
            node -e "import('./api/api/search.js').then(()=>console.log('✅ api/api/search.js import OK')).catch(e=>{console.error(e);process.exit(1)})"
          else
            echo "❌ No serverless function found at api/search.js or api/api/search.js"
            exit 1
          fi
