name: Client (build)

on:
  push:
    branches: [ main ]
    paths:
      - "client/**"
      - ".github/workflows/client.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "client/**"
      - ".github/workflows/client.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install deps
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Verify dist exists
        run: test -d dist && echo "✅ dist/ built"
